//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.UserMessage = new HashSet<UserMessage>();
        }
    
        public int Id { get; set; }
        public string Message1 { get; set; }
        public System.DateTime RecDate { get; set; }
    
        public virtual ICollection<UserMessage> UserMessage { get; set; }
    }
}
