//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserMessage = new HashSet<UserMessage>();
            this.UserMessage1 = new HashSet<UserMessage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public bool IsOnline { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastOnlineDate { get; set; }
    
        public virtual ICollection<UserMessage> UserMessage { get; set; }
        public virtual ICollection<UserMessage> UserMessage1 { get; set; }
    }
}
