//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserMessage = new HashSet<UserMessage>();
            this.UserMessage1 = new HashSet<UserMessage>();
        }
    
        public int Id { get; set; }
        public string ChatName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<System.DateTime> LastOnlineDate { get; set; }
    
        public virtual ICollection<UserMessage> UserMessage { get; set; }
        public virtual ICollection<UserMessage> UserMessage1 { get; set; }
    }
}
